USE master
GO

-- move DTCORP datafile

ALTER DATABASE DTCORP MODIFY FILE (NAME = DTCORP_Data, FILENAME = N'P:\MSSQL$ISTOPR\DATA\DTCORP_Data.mdf')
GO
ALTER DATABASE DTCORP MODIFY FILE (NAME = DTCORP_log, FILENAME = N'L:\MSSQL$ISTOPR\LOG\DTCORP_Log.ldf')
GO
ALTER DATABASE DTCORP MODIFY FILE (NAME = DTCORP_Indx, FILENAME = N'G:\MSSQL$ISTOPR\DATA\DTCORP_Indx.ndf')
GO

-- move SIOPMCORP datafile

ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = SIOPMCRP_Data	, FILENAME = N'P:\MSSQL$ISTOPR\DATA\SIOPMCRP_Data.mdf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = SIOPMCRP_Log	, FILENAME = N'L:\MSSQL$ISTOPR\LOG\SIOPMCRP_Log.ldf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Data1	, FILENAME = N'T:\MSSQL$ISTOPR\DATA\TELLOG_Data1.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = ENC_Data1	, FILENAME = N'E:\MSSQL$ISTOPR\DATA\ENC_Data1.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = HISOCR_Data	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\HISOCR_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = HISSRV_Data	, FILENAME = N'P:\MSSQL$ISTOPR\DATA\HISSRV_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = HSHPES_Data	, FILENAME = N'P:\MSSQL$ISTOPR\DATA\HSHPES_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = ENC_Indx	, FILENAME = N'F:\MSSQL$ISTOPR\DATA\ENC_Indx.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = OCR_Indx	, FILENAME = N'I:\MSSQL$ISTOPR\DATA\OCR_Indx.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = PTRLOG_Indx	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\PTRLOG_Indx.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Indx 	, FILENAME = N'H:\MSSQL$ISTOPR\DATA\TELLOG_Indx .ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = ENC_Data2	, FILENAME = N'E:\MSSQL$ISTOPR\DATA\ENC_Data2.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = PES_Data	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\PES_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = PTRLOG_Data	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\PTRLOG_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TEL_Data	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\TEL_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Data2	, FILENAME = N'T:\MSSQL$ISTOPR\DATA\TELLOG_Data2.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TMP_Data	, FILENAME = N'P:\MSSQL$ISTOPR\DATA\TMP_Data.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = ENC_Data3	, FILENAME = N'E:\MSSQL$ISTOPR\DATA\ENC_Data3.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = OCR_Data1	, FILENAME = N'O:\MSSQL$ISTOPR\DATA\OCR_Data1.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = OCR_Data2	, FILENAME = N'O:\MSSQL$ISTOPR\DATA\OCR_Data2.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = OCR_Data3	, FILENAME = N'O:\MSSQL$ISTOPR\DATA\OCR_Data3.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Data3	, FILENAME = N'T:\MSSQL$ISTOPR\DATA\TELLOG_Data3.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Data4	, FILENAME = N'T:\MSSQL$ISTOPR\DATA\TELLOG_Data4.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = TELLOG_Data5	, FILENAME = N'T:\MSSQL$ISTOPR\DATA\TELLOG_Data5.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = SIOPMCRP_Indx	, FILENAME = N'G:\MSSQL$ISTOPR\DATA\SIOPMCRP_Indx.ndf')
GO
ALTER DATABASE SIOPMCORP MODIFY FILE (NAME = FGITEL_Indx	, FILENAME = N'P:\MSSQL$ISTOPR\DATA\FGITEL_Indx.ndf')
GO

-- STOP INSTANCE
-- RENAME FOLDER NAME IN EVERY LOGICAL DRIVE, 
-- PAY ATTENTION IN "P:\" DRIVE TO PERMISSION ON SYSTEM DATABASES FILES
-- START INSTANCE

/*
select 
name, physical_name from sys.master_files where database_id = DB_ID('DTCORP')
go
select 
name, physical_name from sys.master_files where database_id = DB_ID('SIOPMCRP')
go
*/

